### PR TITLE
attempted fix at images

### PR DESCRIPTION
**Pull request by mayaankvad**
../ makes u move back a directory. But you dont have to do that here. LLLL

### CODE REVIEW

**Comment by Asap7772** [comment]
lol I know what that problem was. I was just going to add something else before making a pull request (i.e format the website better)

**Comment by Asap7772** [comment]
thanks tho

**Comment by mayaankvad** [comment]
Im still giving u an L

**Comment by Asap7772** [comment]
Arav started this so he had a few formatting issues. I just created a git repo so we could use git pages. It is pretty useful.

**Comment by mayaankvad** [comment]
..........

**Pull request closed without merging**
